services:
  dposewebcam:
    network_mode: "host"
    container_name: dpose-hands
    image: dpose-hands
    command:  tail -f /dev/null
    volumes:
      - .:/app/dpose
      - /scratch/spare/nvasilik/data:/app/dpose/data
      #- /tmp/.X11-unix:/tmp/.X11-unix
      #- /dev/video0:/dev/video0
      #- /dev/video1:/dev/video1
      #all network interfaces
      #- /dev:/dev
    shm_size: 400G
    deploy:
      resources:
        limits:
          cpus: '40'
          memory: 400G
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['3']
    privileged: true
    #environment:
      #- DISPLAY=$DISPLAY 
      #- RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      #- ROS_DOMAIN_ID=55